text = '''
  "Gambler": [Charlatan, Demagogue, Entertainer, Highwayman, Rapscallion, Rogue],
  "Ghost Strider": [Captain, Outlaw Chief, Targeteer, Vampire Hunter],
  "Giant Slayer": [Daemon Slayer],
  "Grail Knight": [Captain, Courtier, Explorer, Faceless, Noble Lord, Politician],
  "Grail Pilgrim": [Battle Pilgrim, Carcassonne Shepherd, Mercenary, Herrimault, Vagabond],
  "Grandmaster": [Captain, Champion, Noble Lord, Witch Hunter],
  "Grave Robber": [Cat Burglar, Ex-Convict, Fence, Rat Catcher, Student, Thief],
  "Grave Warden": [Grave Robber, Initiate, Militiaman, Temple Guardian, Vampire Hunter, Watchman],
  "Guild Master": [Crime Lord, Politician, Racketeer],
  "Hag Mother": [],
  "Hag Witch": [Demagogue, Hag Mother, Politician, Witch],
  "Hedge Wizard": [Apprentice Wizard, Charlatan, Initiate, Outlaw, Vagabond],
  "Hedgecraft Apprentice": [Apothecary, Apprentice Wizard, Barber-Surgeon, Charlatan,
Hedge Wizard, Hedge Master, Initiate (Ranald, Taal & Rhya), Outlaw, Scribe,
Zealot],
  "Hedge Master": [Artisan, Hedgewise, Scholar, Spy, Witch],
  "Hedgewise": [Physician, Scout, Warlock],
  "Herald": [Agitator, Courtier, Entertainer, Explorer, Politician, Squire],
  "Herrimault": [Demagogue, Grail Pilgrim, Scout, Thief, Vagabond, Veteran],
  "High Priest": [Politician, Scholar, Witch Hunter],
  "Highwayman": [Agitator, Duellist, Master Thief, Outlaw Chief, Sergeant],
  "Horned Hunter": [Hunter, Militiaman, Outlaw, Scout, Vagabond],
  "Horse Archer": [Captain, Horse Master, Mercenary, Scout, Steppes Nomad, Targeteer, Veteran],
  "Horse Coper": [Burgher, Charlatan, Horse Master, Merchant, Rogue],
  "Horse Master": [Ataman, Drover, Horse Archer, Horse Coper, Merchant, Sergeant, Winged Lancer],
  "Hunter": [Animal Trainer, Bounty Hunter, Charcoal-Burner, Fieldwarden, Kithband Warrior,
Miner, Scout, Soldier, Targeteer],
  "Ice Maiden": [Courtier, Ice Witch, Scout, Sergeant, Veteran, Witch],
  "Ice Witch": [Ambassador, Captain],
  "Initiate": [Barber-Surgeon, Demagogue, Friar, Lay Priest, Priest, Scribe, Zealot],
  "Innkeeper": [Burgher, Farmer, Fence, Merchant, Outlaw, Smuggler],
  "Interrogator": [Physician, Racketeer, Thief],
  "Jailer": [Bailiff, Bodyguard, Interrogator, Rat Catcher, Watchman],
  "Journeyman Runesmith": [Master Runesmith, Scholar, Shieldbreaker],
  "Journeyman Wizard": [Charlatan, Master Wizard, Scholar],
  "Judical Champion": [Assassin, Champion, Sergeant, Witch Hunter, Zealot],
  "Killer of the Dead": [],
  "Kislevite Kossar": [Bounty Hunter, Mercenary, Sergeant, Shieldbreaker, Veteran],
  "Kithband Warrior": [Hunter, Outrider, Scout, Vagabond, Veteran],
  "Knight": [Captain, Initiate, Knight of the Inner Circle, Noble Lord, Vampire Hunter],
  "Knight Errant": [Knight of the Realm],
  "Knight of the Blazing Sun": [Captain, Champion, Explorer, Initiate, Knight of the Inner Circle],
  "Knight of the Inner Circle": [Captain, Champion, Noble Lord, Witch Hunter],
  "Knight of the Raven": [Captain, Champion, Killer of the Dead, Knight of the Inner Circle, Witch Hunter],
  "Knight of the Realm": [Captain, Courtier, Explorer, Faceless, Noble Lord, Politician, Questing Knight],
  "Knight of the Verdant Field": [Priest, Scout, Veteran ],
  "Knight Panther": [Captain, Champion, Knight of the Inner Circle, Veteran, Witch Hunter],
  "Lamplighter": [Agitator, Burgher, Entertainer, Initiate, Servant, Smuggler, Toll Keeper, Watchman],
  "Lay Priest": [Friar, Prelate, Priest ],
  "Litigant": [Agitator, Demagogue, Guild Master, Merchant, Politician, Scholar],
  "Man-at-Arms": [Carcassonne Shepherd, Herrimault, Outlaw, Outrider, Veteran, Yeoman],
  "Marauder": [Chaos Warrior, Mercenary, Reaver, Slaver, Warleader],
  "Marine": [Mate, Outlaw, Sergeant, Smuggler, Thug],
  "Master Runesmith": [Runelord, Scholar, Veteran],
  "Master Thief": [Crime Lord, Explorer, Outlaw Chief, Targeteer],
  "Master Vigilant": [Master Wizard, Spy, Vampire Hunter, Witch Hunter, Wizard Lord],
  "Master Wizard": [Explorer, Scholar, Wizard Lord],
  "Mate": [Explorer, Merchant, Navigator, Sea Captain],
  "Mediator": [Demagogue, Herrimault, Rogue, Village Elder],
  "Mercenary": [Bodyguard, Bounty Hunter, Outlaw, Sergeant, Shieldbreaker, Veteran],
  "Merchant": [Farmer, Guild Master, Militiaman, Politician, Racketeer, Spy],
  "Messenger": [Cartographer, Coachman, Herald, Kithband Warrior, Outrider, Roadwarden, Scout, Soldier],
  "Militiaman": [Artisan, Fieldwarden, Mercenary, Messenger, Outlaw, Sergeant, Thief],
  "Miner": [Charcoal-Burner, Engineer, Mercenary, Scout, Shieldbreaker, Smuggler],
  "Minstrel": [Charlatan, Demagogue, Highwayman, Spy, Student],
  "Monk": [Abbot, Demagogue, Friar, Physician, Priest, Scholar, Steward, Zealot],
  "Muleskinner": [Animal Trainer, Burgher, Highwayman, Merchant, Messenger, Outlaw, Scout],
  "Mystic": [Charlatan, Demagogue, Hedge Wizard, Rogue],
  "Navigator": [Artisan, Cartographer, Explorer, Scholar, Sea Captain],
  "Newssheet Vendor": [Agitator, Demagogue, Entertainer, Messenger, Pamphleteer, Rogue, Scribe, Zealot],
  "Noble": [Courtier, Dilettante, Pistolier, Politician, Rogue, Squire, Student],
  "Noble Lord": [Captain, Knight, Scholar, Sea Captain],
  "Norse Berserker": [Mercenary, Pit Fighter, Seaman, Sergeant, Veteran],
  "Outlaw": [Demagogue, Ex-Convict, Highwayman, Thief, Vagabond, Veteran],
  "Outlaw Chief": [Assassin, Captain, Crime Lord, Demagogue],
  "Outrider": [Coachman, Highwayman, Mercenary, Roadwarden, Scout],
  "Pamphleter": [Demagogue, Merchant, Politician, Scholar],
  "Peasant": [Bone Picker, Charcoal-Burner, Farmer, Fisherman, Militiaman, Outlaw, Politician,
Servant, Tradesman, Zealot],
  "Penitent": [Cenobite, Charlatan, Flagellant, Initiate, Vagabond],
  "Physician": [Friar, Guild Master, Scholar, Spy],
  "Pilgrim": [Demagogue, Friar, Initiate, Outlaw, Vagabond, Zealot],
  "Pistolier": [Courtier, Duellist, Knight, Sergeant, Veteran],
  "Pit Fighter": [Bounty Hunter, Mercenary, Protagonist, Troll Slayer, Veteran],
  "Politician": [Courtier, Crime Lord, Demagogue, Noble Lord, Racketeer, Steward],
  "Prelate": [Demagogue, Friar, Politician, Priest],
  "Priest": [Anointed Priest, Flagellant, Lay Priest, Prelate, Scholar, Steward],
  "Protagonist": [Duellist, Ex-Convict, Pit Fighter, Racketeer, Thief, Thug],
  "Questing Knight": [Captain, Courtier, Explorer, Grail Knight, Faceless, Noble Lord, Politician],
  "Racketeer": [Fence, Master Thief, Politician, Outlaw Chief],
  "Raconteur": [Charlatan, Courtier, Demagogue, Entertainer, Herald, Initiate, Rapscallion, Rogue],
  "Rapscallion": [Charlatan, Duellist, Fence, Highwayman, Spy],
  "Rat Catcher": [Animal Trainer, Bone Picker, Cat Burglar, Grave Robber, Jailer, Shieldbreaker, Thief],
  "Reaver": [Marine, Mate, Mercenary, Navigator, Slaver, Ulfwerenar, Veteran, Warleader],
  "River Warden": [Boatman, Marine, Roadwarden, Seaman, Sergeant, Smuggler, Toll Keeper, Verenean Investigator, Wrecker],
  "Roadwarden": [Highwayman, Messenger, Outlaw, Outrider, Scout, Sergeant, Toll Keeper],
  "Rogue": [Charlatan, Demagogue, Entertainer, Ex-Convict, Outlaw, Servant, Thief],
  "Runebearer": [Rat Catcher, Scout, Shieldbreaker, Tomb Robber, Veteran],
  "Runelord": [Captain, Guild Master],
  "Scholar": [Apprentice Wizard, Explorer, Friar, Litigant, Merchant, Physician, Steward],
  "Scourge of God": [Champion, Initiate, Interrogator, Witch Hunter],
  "Scout": [Cartographer, Explorer, Outlaw Chief, Sergeant, Vampire Hunter, Ghost Strider],
  "Scribe": [Agitator, Apprentice Wizard, Cartographer, Initiate, Navigator, Scholar],
  "Sea Captain": [Explorer, Noble Lord, Scholar, Spy],
  "Seaman": [Marine, Mate, Navigator, Rogue, Smuggler],
  "Seer": [Agitator, Charlatan, Maledictor, Vagabond, Vitki, Witch ],
  "Sergeant": [Captain, Duellist, Judicial Champion, Knight],
  "Servant": [Agitator, Burgher, Camp Follower, Innkeeper, Messenger, Spy, Thief, Valet],
  "Sewer Jack": [Mercenary, Rat Catcher, Sergeant, Shieldbreaker, Smuggler, Veteran, Watchman],
  "Shieldbreaker": [Pit Fighter, Runebearer, Sergeant, Smuggler, Tomb Robber, Veteran],
  "Skald": [Agitator, Berserker, Burgher, Freeholder, Marauder, Mercenary, Reaver, Rogue, Seer],
  "Slave": [Clanrat, Clawleader, Any],
  "Slaver": [Captain, Chaos Warrior, Outlaw Chief, Seaman],
  "Smuggler": [Boatman, Charlatan, Ex-Convict, Fence, Ferryman, Seaman, Shieldbreaker,
Thief],
  "Soldier": [Mercenary, Outrider, Sergeant, Vagabond, Veteran, Watchman],
  "Spy": [Assassin, Explorer, Master Thief, Racketeer],
  "Squire": [Knight, Noble, Outlaw, Sergeant, Veteran],
  "Steppes Nomad": [Ataman, Horse Archer, Horse Master, Kossar, Outlaw, Scout, Vagabond],
  "Stevedore": [Boatman, Foreman, Marine, Merchant, Smuggler, Thief, Thug, Tradesman],
  "Steward": [Crime Lord, Fence, Merchant, Noble],
  "Streltsi": [Bounty Hunter, Chekist, Mercenary, Sergeant, Veteran, Watchman, Winged Lancer],
  "Strigany Mystic": [Astrologer, Bone Picker, Charlatan, Entertainer, Hedge Wizard, Rogue, Seer, Thief],
  "Student": [Agitator, Apprentice Wizard, Barber-Surgeon, Cartographer, Engineer, Envoy, Initiate,
Physician, Scholar],
  "Swamp Skimmer": [Mercenary, Peasant, Vagabond],
  "Swampaire": [Grail Pilgrim, Herrimault, Man-at-Arms, Outlaw, Thug, Vagabond, Village Elder, Yeoman],
  "Targeteer": [Assassin, Champion, Duellist, Sergeant],
  "Temple Guardian": [Initiate, Mercenary, Soldier, Squire, Watchman],
  "Thief": [Cat Burglar, Charlatan, Entertainer, Fence, Rogue, Tomb Robber],
  "Thug": [Bodyguard, Ex-Convict, Interrogator, Mercenary, Pit Fighter, Racketeer],
  "Toll Keeper": [Ferryman, Fieldwarden, Highwayman, Outlaw, Soldier, Politician, Thief],
  "Tomb Robber": [Ex-Convict, Fence, Rat Catcher, Shieldbreaker, Thief, Vampire Hunter],
  "Tradesman": [Artisan, Cartographer, Engineer, Envoy, Farmer, Merchant, Militiaman,
Zealot],
  "Troll Slayer": [Giant Slayer],
  "Vagabond": [Bone Picker, Entertainer, Friar, Rapscallion, Scout, Thief, Woodsman],
  "Valet": [Herald, Rogue, Squire, Steward, Student],
  "Vampire Hunter": [Demagogue, Initiate, Knight, Targeteer, Witch Hunter],
  "Verenean Investigator": [Initiate, Scholar, Spy, Witch Hunter],
  "Veteran": [Champion, Farmer, Judicial Champion, Outlaw Chief, Sergeant, Targeteer],
  "Village Elder": [Demagogue, Faceless, Outlaw Chief, Politician, Steward],
  "Wall Warden": [Spy, Steward, Yeoman],
  "Warleader": [Captain, Chaos Warrior, Champion, Veteran],
  "Warlock": [Apprentice Wizard, Charlatan, Outlaw, Scribe, Vagabond],
  "Warrior Priest": [High Priest, Knight, Prelate, Witch Hunter],
  "Watchman": [Mercenary, Racketeer, Roadwarden, Sergeant, Soldier, Tradesman],
  "Whaler": [Freeholder, Marauder, Navigator, Reaver, Veteran],
  "Winged Lancer": [Captain, Horse Master, Scout, Veteran],
  "Wise Woman": [Demagogue, Hag Witch, Hedge Witch, Politician, Steppes Nomad],
  "Witch": [Apprentice Wizard, Charlatan, Outlaw, Vagabond, Warlock],
  "Wtich Hunter": [Captain, Champion, Demagogue, Initiate, Knight of the Inner Circle],
  "Wizard Lord": [Explorer, Guild Master],
  "Woodsman": [Hunter, Militiaman, Outlaw, Scout, Vagabond],
  "Wrecker": [Boatman, Marine, Outlaw, Thief, Veteran],
  "Yeoman": [Faceless, Mercenary, Outlaw Chief, Scout, Sergeant],
  "Zealot": [Agitator, Initiate, Flagellant, Friar, Outlaw]'''

text = [t.strip() for t in text.split('],') if t.strip()]
dictionary = {}

for t in text:
    split = t.split(':')
    
    key = split[0].strip("\"")
    val_list = split[1].split(',')
    
    for i in range(len(val_list)):
        val_list[i] = val_list[i].strip()
        if '[' in val_list[i]:
            val_list[i] = val_list[i][1:]
        if ']' in val_list[i]:
            val_list[i] = val_list[i][:-1]

    dictionary[key] = val_list

import json
print(json.dumps(dictionary))